site_title = "MyArxiv"
limit_days = 30
cache_url = "https://xuzhaoli.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.MA"
title = "Multiagent Systems"

[[sources]]
limit = 150
category = "cs.SY"
title = "Systems and Control (CS)"

[[sources]]
limit = 150
category = "eess.SY"
title = "Systems and Control (EESS)"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"